on:
  release:
    types:
      - created
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: ./scripts/build.sh
      
      - run: cd dist/package/stat_qt_660; zip -r ../../../static_qt_660-package.zip .
      - run:
          gh release upload ${{ github.event.release.tag_name }}
          static_qt_660-package.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}